[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
sdk = { workspace = true }
solana-program = { workspace = true }
